services:
  exporter:
    build: services/exporter/.
    container_name: 3m-exporter
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${EXPORTER_HOST_NAME}
      VIRTUAL_HOST: ${EXPORTER_HOST_NAME}
      VIRTUAL_PORT: 8080
      
    volumes:
      - ./services/exporter/src:/src
    