version: "3"
services:
  editor:
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${HOST_NAME}
      VIRTUAL_HOST: ${HOST_NAME}
      VIRTUAL_PORT: 8080
      CONTENT_SECURITY_POLICY: "default-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: https://ajax.googleapis.com https://code.jquery.com https://maxcdn.bootstrapcdn.com; img-src 'self' https: data: blob:; connect-src 'self'; style-src-elem 'self' 'unsafe-inline' fonts.googleapis.com maxcdn.bootstrapcdn.com; font-src 'self' fonts.gstatic.com;"
    networks:
      proxy:

networks:
  proxy:
    external: true
    name: ${PROXY_NETWORK}