version: "3"
services:
  exporter:
    build: services/exporter/.
    container_name: 3m-exporter
    entrypoint: uvicorn main:app --reload --host 0.0.0.0 --port 8080
    ports:
      - 8082:8080
    volumes:
      - ./services/exporter/src:/src
    