version: "3"
services:
  editor:
    build: .
    container_name: 3m-docker
    image: swissartresearx/3m-docker:latest
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - db-data:/opt/exist/webapp/WEB-INF/data/
      - editor-data:/opt/3m
      - editor-data:/opt/3M

volumes:
  db-data:
  editor-data: