services:
  exporter:
    build: services/exporter/.
    container_name: 3m-exporter
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${EXPORTER_HOST_NAME}
      VIRTUAL_HOST: ${EXPORTER_HOST_NAME}
      VIRTUAL_PORT: 8080
    networks:
      proxy:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
      
    volumes:
      - ./services/exporter/src:/src
    